"use client";

import { CLOUDINARY_IMAGE_WIDTHS, cloudinaryImageUrl } from "@/lib/cloudinary-delivery";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import type { User } from "firebase/auth";
import { useFavorites } from "@/context/favorites";
import { loadProfile, saveProfile, type ProfileResponse } from "@/lib/profile/client";
import { FallbackImage } from "@/components/ui/FallbackImage";

type RunItem = { id:string; monthKey:string; publicName:string; caption:string|null; wilaya:string|null; status:string; publicState:"public"|"private"; isWinner:boolean; proofImage:{secureUrl:string;width:number;height:number}|null };
type RunEdit = { publicName:string; caption:string; wilaya:string };

export function AccountPageClient() {
  const { totalFavoriteCount } = useFavorites();
  const [user, setUser] = useState<User | null>(null), [authReady,setAuthReady]=useState(false);
  const [profile,setProfile]=useState<ProfileResponse|null>(null), [editing,setEditing]=useState(false), [name,setName]=useState("");
  const [state,setState]=useState<"loading"|"loaded"|"saving"|"success"|"error">("loading"), [message,setMessage]=useState("");
  const [runs,setRuns]=useState<RunItem[]>([]), [cursor,setCursor]=useState<string|null>(null), [runsLoading,setRunsLoading]=useState(false);
  const [runsError,setRunsError]=useState("");
  const [editRun,setEditRun]=useState<RunItem|null>(null), [removeRun,setRemoveRun]=useState<RunItem|null>(null);
  const [runNotice,setRunNotice]=useState("");

  const authFetch=useCallback(async(nextUser:User,url:string,init?:RequestInit)=>fetch(url,{...init,cache:"no-store",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await nextUser.getIdToken()}`,...init?.headers}}),[]);
  const loadRuns=useCallback(async(nextUser:User,append=false,nextCursor?:string|null)=>{setRunsLoading(true);setRunsError("");try{const url=new URL("/api/account/run-club",location.origin);if(append&&nextCursor)url.searchParams.set("cursor",nextCursor);const response=await authFetch(nextUser,url.pathname+url.search);const body=await response.json();if(!response.ok)throw new Error(body.error||"Run Club activity is unavailable.");setRuns(current=>append?[...current,...body.submissions]:body.submissions);setCursor(body.nextCursor);}catch(error){setRunsError(error instanceof Error?error.message:"Run Club activity is unavailable.");}finally{setRunsLoading(false);}},[authFetch]);
  useEffect(()=>{let unsubscribe:(()=>void)|undefined;import("@/lib/firebase/client").then(async({auth})=>{const {onAuthStateChanged}=await import("firebase/auth");unsubscribe=onAuthStateChanged(auth,next=>{setUser(next);setAuthReady(true);if(!next){setProfile(null);setRuns([]);setCursor(null);setEditing(false);setMessage("");}});});return()=>unsubscribe?.();},[]);
  useEffect(()=>{if(!user)return;setState("loading");Promise.all([loadProfile(user),loadRuns(user)]).then(([next])=>{setProfile(next);setName(next.identity.displayName??"");setState("loaded");}).catch(error=>{setMessage(error.message);setState("error");});},[user,loadRuns]);
  useEffect(()=>{if(!user)return;const refresh=()=>{if(document.visibilityState==="visible")void loadRuns(user);};window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",refresh);return()=>{window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",refresh);};},[user,loadRuns]);
  async function saveName(event:FormEvent){event.preventDefault();if(!user)return;const trimmed=name.trim();if(trimmed.length<2){setMessage("Enter your display name.");setState("error");return;}setState("saving");setMessage("");try{const next=await saveProfile(user,trimmed);setProfile(next);setName(next.identity.displayName??"");setEditing(false);setState("success");}catch(error){setMessage(error instanceof Error?error.message:"Could not save your name.");setState("error");}}
  async function editRunRequest(id:string,values:RunEdit){if(!user)return false;const response=await authFetch(user,`/api/account/run-club/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(values)});const body=await response.json();if(!response.ok){setMessage(body.error||"Run Club request failed.");return false;}setRuns(current=>current.map(run=>run.id===id?{...run,...values,caption:values.caption||null,wilaya:values.wilaya||null,status:"edit_requested"}:run));setEditRun(null);setRunNotice("EDIT REQUEST SUBMITTED.");return true;}
  async function removeRunPost(id:string){if(!user)return;const response=await authFetch(user,`/api/account/run-club/${encodeURIComponent(id)}`,{method:"DELETE"});const body=await response.json();if(!response.ok){setMessage(body.error||"Run Club request failed.");return;}setRuns(current=>current.map(run=>run.id===id?{...run,status:"removed",publicState:"private"}:run));setRemoveRun(null);setRunNotice("RUN CLUB POST REMOVED.");}
  async function signOut(){const {auth}=await import("@/lib/firebase/client");const {signOut}=await import("firebase/auth");await signOut(auth);}
  if(!authReady)return <AccountState label="CHECKING YOUR ACCOUNT…"/>; if(!user)return <AccountState label="SIGN IN TO VIEW YOUR ACCOUNT." action/>; if(state==="loading")return <AccountState label="LOADING ACCOUNT…"/>;
  return <div className="accountPage"><header className="accountPage__head"><span>ACCOUNT</span><h1>MY ACCOUNT</h1></header>{state==="success"?<p className="accountFeedback accountFeedback--success">ACCOUNT DETAILS SAVED.</p>:null}{runNotice?<p className="accountFeedback accountFeedback--success" role="status">{runNotice}</p>:null}{state==="error"&&message?<p className="accountFeedback accountFeedback--error" role="alert">{message}</p>:null}<div className="accountGrid">
    <div className="accountColumn"><section className="accountCard accountIdentity"><small>CUSTOMER</small><div className="accountNameLine"><h2>{profile?.identity.displayName||"RUN213 CUSTOMER"}</h2><button aria-label="Edit display name" title="Edit display name" onClick={()=>setEditing(true)}>✎</button></div><p>{profile?.identity.email}</p>{profile?.identity.createdAt?<p>Member since {new Date(profile.identity.createdAt).toLocaleDateString()}</p>:null}{editing?<form className="accountNameEdit" onSubmit={saveName}><label>DISPLAY NAME<input autoFocus value={name} onChange={event=>setName(event.target.value)}/></label><div><button disabled={state==="saving"}>{state==="saving"?"SAVING…":"SAVE"}</button><button type="button" onClick={()=>setEditing(false)}>CANCEL</button></div></form>:null}</section>
    <section className="accountCard accountSignout"><div><h2>SIGN OUT</h2><p>Guest-order access stays on this device.</p></div><button onClick={signOut}>SIGN OUT</button></section><section className="accountCard"><h2>ACCOUNT ACTIVITY</h2><nav className="accountActivity"><Activity href="/orders" lightIcon="/icons/order-bag.png" darkIcon="/icons/order-bag-dark.png" label="MY ORDERS"/><Activity href="/favorites" lightIcon="/icons/heart.png" darkIcon="/icons/heart-dark.png" label="FAVORITES" detail={`${totalFavoriteCount} SAVED`}/><Activity href="/favorites" lightIcon="/icons/save.png" darkIcon="/icons/save-dark.png" label="SAVED"/><Activity href="/run-club" lightIcon="/icons/running.png" darkIcon="/icons/running-dark.png" label="RUN CLUB"/></nav></section></div>
    <section className="accountCard accountRuns"><div className="accountRuns__heading"><h2>MY RUN CLUB ACTIVITY</h2><button type="button" disabled={runsLoading} onClick={()=>void loadRuns(user)}>{runsLoading?"REFRESHING…":"REFRESH"}</button></div>{runsError?<div className="accountRuns__error" role="alert"><p>{runsError}</p><button type="button" disabled={runsLoading} onClick={()=>void loadRuns(user)}>RETRY</button></div>:runs.length?runs.map(run=><RunCard key={run.id} run={run} onEdit={setEditRun} onRemove={setRemoveRun}/>):<p className="accountMuted">No securely linked Run Club submissions yet.</p>}{cursor&&!runsError?<button className="accountLoadMore" disabled={runsLoading} onClick={()=>void loadRuns(user,true,cursor)}>{runsLoading?"LOADING…":"LOAD MORE"}</button>:null}</section>
  </div>{editRun?<EditRunModal run={editRun} onClose={()=>setEditRun(null)} onSubmit={values=>editRunRequest(editRun.id,values)}/>:null}{removeRun?<RemoveRunModal onClose={()=>setRemoveRun(null)} onConfirm={()=>void removeRunPost(removeRun.id)}/>:null}</div>;
}
function Activity({href,lightIcon,darkIcon,label,detail}:{href:string;lightIcon:string;darkIcon:string;label:string;detail?:string}){return <Link href={href}><span><picture><source media="(prefers-color-scheme: dark)" srcSet={darkIcon}/><FallbackImage src={lightIcon} fallbackSrc={lightIcon} alt="" aria-hidden width={36} height={36}/></picture>{label}</span><b>{detail||"VIEW"} →</b></Link>}
function statusLabel(run:RunItem){if(run.status==="edit_requested")return "EDIT REQUESTED";if(run.status==="pending")return "PENDING REVIEW";if(run.status==="rejected")return "REJECTED";if(run.status==="removed"||run.status==="removal_requested")return "REMOVED";return run.status.toUpperCase();}
function RunCard({run,onEdit,onRemove}:{run:RunItem;onEdit:(run:RunItem)=>void;onRemove:(run:RunItem)=>void}){const canEdit=run.status==="pending"||run.status==="approved";const usefulVisibility=run.status==="approved";return <article className="accountRunCard">{run.proofImage?<FallbackImage src={cloudinaryImageUrl(run.proofImage.secureUrl, { width: CLOUDINARY_IMAGE_WIDTHS.adminThumbnail })} fallbackSrc="/placeholders/community-proof-placeholder.webp" alt={`Run proof submitted by ${run.publicName}`} width={96} height={96} sizes="96px" unoptimized/>:<div className="accountRunCard__noImage" aria-label="Proof image unavailable"/>}<div><div className="accountRunMeta"><span>{run.monthKey}</span><b>{statusLabel(run)}</b>{usefulVisibility?<small className={`accountRunVisibility accountRunVisibility--${run.publicState}`}>{run.publicState==="public"?"PUBLIC":"HIDDEN"}</small>:null}{run.isWinner?<em>WINNER</em>:null}</div><dl className="accountRunDetails"><div><dt>PUBLIC NAME</dt><dd>{run.publicName}</dd></div><div><dt>WILAYA</dt><dd>{run.wilaya||"—"}</dd></div>{run.caption?<div><dt>CAPTION</dt><dd>{run.caption}</dd></div>:null}</dl>{canEdit?<div className="accountRunActions"><button onClick={()=>onEdit(run)}>{run.status==="pending"?"EDIT":"REQUEST EDIT"}</button><button className="accountRunActions__remove" onClick={()=>onRemove(run)}>REMOVE POST</button></div>:null}</div></article>}
function EditRunModal({run,onClose,onSubmit}:{run:RunItem;onClose:()=>void;onSubmit:(values:RunEdit)=>Promise<boolean>}){const [values,setValues]=useState<RunEdit>({publicName:run.publicName,wilaya:run.wilaya??"",caption:run.caption??""}),[saving,setSaving]=useState(false);async function submit(event:FormEvent){event.preventDefault();setSaving(true);await onSubmit(values);setSaving(false);}return <div className="accountRunModal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose();}}><section role="dialog" aria-modal="true" aria-labelledby="edit-run-title" onMouseDown={event=>event.stopPropagation()}><header><h2 id="edit-run-title">EDIT RUN CLUB POST</h2><button type="button" aria-label="Close edit modal" disabled={saving} onClick={onClose}>×</button></header><form onSubmit={submit}><label>PUBLIC NAME<input required minLength={2} maxLength={80} value={values.publicName} onChange={e=>setValues({...values,publicName:e.target.value})}/></label><label>WILAYA<input maxLength={60} value={values.wilaya} onChange={e=>setValues({...values,wilaya:e.target.value})}/></label><label>CAPTION<textarea maxLength={280} value={values.caption} onChange={e=>setValues({...values,caption:e.target.value})}/></label><div><button className="accountRunModal__primary" disabled={saving}>{saving?"SUBMITTING…":"SUBMIT EDIT REQUEST"}</button><button type="button" className="accountRunModal__neutral" disabled={saving} onClick={onClose}>CANCEL</button></div></form></section></div>}
function RemoveRunModal({onClose,onConfirm}:{onClose:()=>void;onConfirm:()=>void}){return <div className="accountRunModal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section role="dialog" aria-modal="true" aria-labelledby="remove-run-title" onMouseDown={event=>event.stopPropagation()}><header><h2 id="remove-run-title">REMOVE THIS RUN CLUB POST?</h2><button type="button" aria-label="Close removal modal" onClick={onClose}>×</button></header><p>It will disappear from your profile and the public Run Club community.</p><div className="accountRunModal__actions"><button className="accountRunModal__danger" type="button" onClick={onConfirm}>REMOVE POST</button><button className="accountRunModal__neutral" type="button" onClick={onClose}>KEEP POST</button></div></section></div>}
function AccountState({label,action=false}:{label:string;action?:boolean}){return <div className="accountPage accountState"><p>{label}</p>{action?<button onClick={()=>window.dispatchEvent(new Event("run213:open-auth"))}>SIGN IN</button>:null}</div>}
