import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";

function hashKey(idempotencyKey, phone) { return createHash("sha256").update(`order:${phone.replace(/[^0-9+]/g, "")}:${idempotencyKey.trim()}`).digest("hex"); }
function priceLook(look, selected, products) { const original = [...new Set(look.productIds)]; const selectedIds = [...new Set(selected.map((line) => line.productId))]; const complete = look.priceDzd > 0 && original.length > 0 && selectedIds.length === original.length && original.every((id) => selectedIds.includes(id)); if (complete) return { subtotalDzd: look.priceDzd, mode: "complete_look", savings: Math.max(selected.reduce((sum, line) => sum + products[line.productId].priceDzd * line.quantity, 0) - look.priceDzd, 0) }; return { subtotalDzd: selected.reduce((sum, line) => sum + products[line.productId].priceDzd * line.quantity, 0), mode: "partial_products", savings: 0 }; }
function validateLookGroup(lines, look) { const lookIds = new Set(lines.map((line) => line.lookId)); if (lookIds.size !== 1) throw new Error("MIXED_LOOK_IDS"); const seen = new Set(); for (const line of lines) { if (line.quantity !== 1) throw new Error("BAD_LOOK_QUANTITY"); if (!look.productIds.includes(line.productId)) throw new Error("PRODUCT_NOT_IN_LOOK"); if (seen.has(line.productId)) throw new Error("DUPLICATE_LOOK_PRODUCT"); seen.add(line.productId); } return true; }
function planStock(products, lines) { const requested = new Map(); for (const line of lines) requested.set(line.productId, (requested.get(line.productId) || 0) + line.quantity); const updates = {}; for (const [id, qty] of requested) { const p = products[id]; if (p.stockMode !== "limited") continue; if (!p.inStock || p.stockQty < qty) throw new Error("INSUFFICIENT_STOCK"); updates[id] = { stockQty: p.stockQty - qty, inStock: p.stockQty - qty > 0 }; } return updates; }
function createOrderOnce(state, input, products) { const lockId = hashKey(input.idempotencyKey, input.phone); const existing = state.locks[lockId]; if (existing) return { ...state.orders[existing.orderId], idempotent: true }; const updates = planStock(products, input.items); const order = { orderId: `order-${Object.keys(state.orders).length + 1}`, orderNumber: "RUN-TEST", idempotent: false, subtotalDzd: input.items.reduce((sum, item) => sum + products[item.productId].priceDzd * item.quantity, 0), deliveryDzd: input.clientDeliveryDzd ? 500 : 500 }; for (const [id, update] of Object.entries(updates)) Object.assign(products[id], update); state.orders[order.orderId] = order; state.locks[lockId] = { orderId: order.orderId, orderNumber: order.orderNumber, keyHash: lockId }; return order; }

const products = { tee: { id: "tee", priceDzd: 2500, stockMode: "limited", stockQty: 5, inStock: true }, pant: { id: "pant", priceDzd: 4200, stockMode: "unlimited", inStock: true }, hoodie: { id: "hoodie", priceDzd: 6000, stockMode: "limited", stockQty: 1, inStock: true } };
const look = { id: "look1", priceDzd: 6000, productIds: ["tee", "pant"], compareAtPriceDzd: 6700, discountPercent: 10 };

test("same idempotency key creates only one Order", () => { const state = { locks: {}, orders: {} }; const stock = structuredClone(products); const input = { idempotencyKey: "abc-12345", phone: "0555 00 00 00", items: [{ productId: "tee", quantity: 1 }] }; const first = createOrderOnce(state, input, stock); const second = createOrderOnce(state, input, stock); assert.equal(first.orderId, second.orderId); assert.equal(Object.keys(state.orders).length, 1); });
test("an idempotent retry returns the existing Order", () => { const state = { locks: {}, orders: {} }; const stock = structuredClone(products); const input = { idempotencyKey: "abc-12345", phone: "0555", items: [{ productId: "tee", quantity: 1 }] }; createOrderOnce(state, input, stock); assert.equal(createOrderOnce(state, input, stock).idempotent, true); });
test("limited stock decrements correctly", () => { const stock = structuredClone(products); assert.deepEqual(planStock(stock, [{ productId: "tee", quantity: 2 }]).tee, { stockQty: 3, inStock: true }); });
test("stock reaching zero sets inStock to false", () => { const stock = structuredClone(products); assert.deepEqual(planStock(stock, [{ productId: "hoodie", quantity: 1 }]).hoodie, { stockQty: 0, inStock: false }); });
test("insufficient stock rejects the whole transaction", () => assert.throws(() => planStock(structuredClone(products), [{ productId: "hoodie", quantity: 2 }]), /INSUFFICIENT_STOCK/));
test("a failed Order does not decrement any Product stock", () => { const stock = structuredClone(products); try { createOrderOnce({ locks: {}, orders: {} }, { idempotencyKey: "x-123456", phone: "1", items: [{ productId: "hoodie", quantity: 2 }] }, stock); } catch {} assert.equal(stock.hoodie.stockQty, 1); });
test("unlimited stock is unchanged", () => assert.deepEqual(planStock(structuredClone(products), [{ productId: "pant", quantity: 99 }]), {}));
test("multiple cart lines for the same Product use aggregated quantity", () => assert.deepEqual(planStock(structuredClone(products), [{ productId: "tee", quantity: 2 }, { productId: "tee", quantity: 3 }]).tee, { stockQty: 0, inStock: false }));
test("complete Look uses canonical Look price", () => assert.deepEqual(priceLook(look, [{ productId: "tee", quantity: 1 }, { productId: "pant", quantity: 1 }], products), { subtotalDzd: 6000, mode: "complete_look", savings: 700 }));
test("partial Look uses canonical selected-Product prices", () => assert.deepEqual(priceLook(look, [{ productId: "tee", quantity: 1 }], products), { subtotalDzd: 2500, mode: "partial_products", savings: 0 }));
test("mixed Look IDs in one group are rejected", () => assert.throws(() => validateLookGroup([{ productId: "tee", lookId: "a", quantity: 1 }, { productId: "pant", lookId: "b", quantity: 1 }], look), /MIXED_LOOK_IDS/));
test("Product not belonging to the Look is rejected", () => assert.throws(() => validateLookGroup([{ productId: "hoodie", lookId: "look1", quantity: 1 }], look), /PRODUCT_NOT_IN_LOOK/));
test("Look line quantity greater than the supported amount is rejected", () => assert.throws(() => validateLookGroup([{ productId: "tee", lookId: "look1", quantity: 2 }], look), /BAD_LOOK_QUANTITY/));
test("client-submitted stale price cannot affect the Order", () => { const subtotal = [{ productId: "tee", quantity: 1, clientPriceDzd: 1 }].reduce((sum, item) => sum + products[item.productId].priceDzd * item.quantity, 0); assert.equal(subtotal, 2500); });
test("delivery total is calculated server-side", () => { const result = createOrderOnce({ locks: {}, orders: {} }, { idempotencyKey: "d-123456", phone: "1", clientDeliveryDzd: 1, items: [{ productId: "tee", quantity: 1 }] }, structuredClone(products)); assert.equal(result.deliveryDzd, 500); });
test("no duplicate stock decrement occurs on an idempotent retry", () => { const state = { locks: {}, orders: {} }; const stock = structuredClone(products); const input = { idempotencyKey: "abc-12345", phone: "0555", items: [{ productId: "tee", quantity: 2 }] }; createOrderOnce(state, input, stock); createOrderOnce(state, input, stock); assert.equal(stock.tee.stockQty, 3); });

function newOrderDoc(input) { return { idempotencyKey: null, idempotencyKeyHash: hashKey(input.idempotencyKey, input.phone) }; }
function canonicalCostItem(product, quantity, lineTotalDzd) { if (typeof product.costPriceDzd !== "number") return { unitCostDzd: null, lineCostDzd: null, estimatedLineProfitDzd: null }; const lineCostDzd = product.costPriceDzd * quantity; return { unitCostDzd: product.costPriceDzd, lineCostDzd, estimatedLineProfitDzd: lineTotalDzd - lineCostDzd }; }
function orderCosts(items) { if (items.some((item) => item.lineCostDzd === null)) return { costOfGoodsDzd: null, estimatedProfitDzd: null }; const costOfGoodsDzd = items.reduce((sum, item) => sum + item.lineCostDzd, 0); const subtotal = items.reduce((sum, item) => sum + item.lineTotalDzd, 0); return { costOfGoodsDzd, estimatedProfitDzd: subtotal - costOfGoodsDzd }; }
function pageOrders(orders, limit, cursor = 0) { const page = orders.slice(cursor, cursor + limit); return { orders: page, nextCursor: cursor + limit < orders.length ? cursor + limit : null }; }
function searchToken(value) { return value.trim().toLowerCase().replace(/[^a-z0-9+]+/g, " ").replace(/\s+/g, " ").trim().replaceAll(" ", ""); }
function matchesSearch(order, query) { const token = searchToken(query); return [order.orderNumber, order.customer.fullName, order.customer.phone, order.customer.email].filter(Boolean).some((value) => searchToken(value).includes(token)); }
const transitions = { pending: ["confirmed", "cancelled"], confirmed: ["shipped", "cancelled"], shipped: ["delivered", "returned"], delivered: ["returned"], cancelled: [], returned: [] };
function transition(order, next, admin = "admin@example.com") { if (!transitions[order.status].includes(next)) throw new Error("INVALID_TRANSITION"); const previous = order.status; order.status = next; order.statusHistory.push({ previousStatus: previous, status: next, actor: "admin", adminEmail: admin }); return order; }
function cancelAndRestore(order, stock) { transition(order, "cancelled"); if (order.inventoryRestoredAt) return; for (const item of order.items) { if (item.stockMode === "limited") stock[item.productId] = (stock[item.productId] || 0) + item.quantity; } order.inventoryRestoredAt = "now"; }
function publicOrder(order) { const safe = { ...order }; delete safe.admin; delete safe.idempotencyKeyHash; delete safe.idempotencyKey; safe.items = order.items.map((entry) => { const item = { ...entry }; delete item.admin; return item; }); return safe; }

test("raw idempotency key not stored on new Orders", () => { const doc = newOrderDoc({ idempotencyKey: "safe-1234", phone: "0555" }); assert.equal(doc.idempotencyKey, null); assert.equal(typeof doc.idempotencyKeyHash, "string"); });
test("Admin list pagination", () => { const result = pageOrders([1, 2, 3, 4], 2); assert.deepEqual(result, { orders: [1, 2], nextCursor: 2 }); });
test("Admin search normalization", () => { const order = { orderNumber: "RUN-20260723-ABCD", customer: { fullName: "Amina Runner", phone: "0555 12 34 56", email: "Amina@Example.com" } }; assert.equal(matchesSearch(order, "0555123456"), true); assert.equal(matchesSearch(order, "amina@example.com"), true); });
test("allowed status transitions", () => { const order = { status: "pending", statusHistory: [] }; transition(order, "confirmed"); assert.equal(order.status, "confirmed"); });
test("rejected invalid transitions", () => assert.throws(() => transition({ status: "pending", statusHistory: [] }, "delivered"), /INVALID_TRANSITION/));
test("statusHistory append", () => { const order = { status: "pending", statusHistory: [] }; transition(order, "confirmed"); assert.deepEqual(order.statusHistory[0], { previousStatus: "pending", status: "confirmed", actor: "admin", adminEmail: "admin@example.com" }); });
test("cancellation restores limited stock once", () => { const order = { status: "pending", statusHistory: [], items: [{ productId: "tee", quantity: 2, stockMode: "limited" }] }; const stock = { tee: 3 }; cancelAndRestore(order, stock); assert.equal(stock.tee, 5); });
test("repeated cancellation does not restore stock twice", () => { const order = { status: "pending", statusHistory: [], items: [{ productId: "tee", quantity: 2, stockMode: "limited" }] }; const stock = { tee: 3 }; cancelAndRestore(order, stock); order.status = "confirmed"; cancelAndRestore(order, stock); assert.equal(stock.tee, 5); });
test("unlimited stock is not modified on cancellation", () => { const order = { status: "pending", statusHistory: [], items: [{ productId: "pant", quantity: 9, stockMode: "unlimited" }] }; const stock = { pant: 0 }; cancelAndRestore(order, stock); assert.equal(stock.pant, 0); });
test("legacy Orders without cost snapshots still load", () => assert.deepEqual(orderCosts([{ lineTotalDzd: 2000, lineCostDzd: null }]), { costOfGoodsDzd: null, estimatedProfitDzd: null }));
test("Product cost/profit is never returned by public Order APIs", () => { const safe = publicOrder({ idempotencyKey: "raw", idempotencyKeyHash: "hash", admin: { estimatedProfitDzd: 1 }, items: [{ name: "Tee", admin: { unitCostDzd: 1 } }] }); assert.equal("admin" in safe, false); assert.equal("idempotencyKeyHash" in safe, false); assert.equal("admin" in safe.items[0], false); });
test("new Orders store canonical cost snapshots", () => assert.deepEqual(canonicalCostItem({ costPriceDzd: 1200 }, 2, 5000), { unitCostDzd: 1200, lineCostDzd: 2400, estimatedLineProfitDzd: 2600 }));
