import "server-only";
import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { z } from "zod";
import { getAdminDb } from "@/lib/firebase/admin";
import type { VerifiedCustomer } from "@/lib/customer-auth";

const editSchema=z.object({caption:z.string().trim().max(280),wilaya:z.string().trim().max(60)}).strict();
export class CustomerRunClubError extends Error{constructor(message:string,public status=400){super(message)}}
const iso=(value:unknown)=>value instanceof Timestamp?value.toDate().toISOString():null;
function safe(doc:FirebaseFirestore.QueryDocumentSnapshot){const d=doc.data(),proof=d.proofImage;const moderation=typeof d.moderationState==="string"?d.moderationState:null;return{id:doc.id,monthKey:String(d.monthKey??""),caption:typeof d.caption==="string"?d.caption:null,wilaya:typeof d.wilaya==="string"?d.wilaya:null,status:moderation??String(d.status??"pending"),publicState:d.status==="approved"&&d.publicVisible!==false?"public":"private",isWinner:d.isWinner===true,proofImage:proof&&typeof proof.secureUrl==="string"?{secureUrl:proof.secureUrl,width:Number(proof.width||1),height:Number(proof.height||1)}:null,createdAt:iso(d.createdAt)};}
export async function listOwnedRuns(customer:VerifiedCustomer,cursor?:string|null){let query=getAdminDb().collection("runClubSubmissions").where("customerUserId","==",customer.uid).orderBy("createdAt","desc").limit(9);if(cursor){const date=new Date(Buffer.from(cursor,"base64url").toString("utf8"));if(!Number.isNaN(date.getTime()))query=query.startAfter(Timestamp.fromDate(date));}const snap=await query.get(),docs=snap.docs.slice(0,8),last=docs.at(-1)?.get("createdAt");return{submissions:docs.map(safe),nextCursor:snap.docs.length>8&&last instanceof Timestamp?Buffer.from(last.toDate().toISOString()).toString("base64url"):null};}
export async function editOwnedRun(customer:VerifiedCustomer,id:string,input:unknown){const values=editSchema.parse(input),ref=getAdminDb().collection("runClubSubmissions").doc(id);await getAdminDb().runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists||snap.get("customerUserId")!==customer.uid)throw new CustomerRunClubError("Submission not found.",404);const d=snap.data()??{};if(d.status==="pending")tx.update(ref,{caption:values.caption,wilaya:values.wilaya,publicCaption:values.caption,publicWilaya:values.wilaya,updatedAt:FieldValue.serverTimestamp(),moderationHistory:FieldValue.arrayUnion({action:"customer_edit",at:new Date().toISOString()})});else if(d.status==="approved"&&d.moderationState!=="removal_requested")tx.update(ref,{moderationState:"edit_requested",pendingRevision:values,editRequestedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp(),moderationHistory:FieldValue.arrayUnion({action:"edit_requested",at:new Date().toISOString()})});else throw new CustomerRunClubError("This submission cannot be edited.",409);});}
export async function removeOwnedRun(customer:VerifiedCustomer,id:string){const ref=getAdminDb().collection("runClubSubmissions").doc(id);await getAdminDb().runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists||snap.get("customerUserId")!==customer.uid)throw new CustomerRunClubError("Submission not found.",404);const d=snap.data()??{};if(d.status==="pending")tx.update(ref,{status:"removed",moderationState:"removed",publicVisible:false,removedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp(),moderationHistory:FieldValue.arrayUnion({action:"customer_cancelled",at:new Date().toISOString()})});else if(d.status==="approved")tx.update(ref,{moderationState:"removal_requested",publicVisible:false,removalRequestedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp(),moderationHistory:FieldValue.arrayUnion({action:"removal_requested",at:new Date().toISOString()})});else throw new CustomerRunClubError("This submission cannot be removed.",409);});}
