import Link from "next/link";
import { EditorialPage, EditorialSection } from "@/components/info/EditorialPage";
import { publicPageMetadata } from "@/lib/seo";
export const metadata = publicPageMetadata({ title: "Privacy Policy", description: "How 213 RUN collects, uses and protects customer, account, analytics and RUN CLUB information.", pathname: "/privacy" });
export default function PrivacyPage() { return <EditorialPage title="PRIVACY POLICY" updated="August 29, 2026">
<EditorialSection title="INFORMATION WE COLLECT"><p>When you place an order or create an account, we may collect information such as your name, email address, phone number, Wilaya, delivery address, delivery mode and order details.</p><p>If you use Favorites, Join the Club or other account features, we may store the information required to provide those features.</p><p>If you submit content to RUN CLUB, we may collect information included in the submission such as your name, contact information, Instagram username, Wilaya, caption and submitted proof image.</p></EditorialSection>
<EditorialSection title="HOW WE USE INFORMATION"><p>We may use information to:</p><ul><li>process and manage orders;</li><li>provide account and Favorites features;</li><li>respond to support requests;</li><li>review and moderate RUN CLUB submissions;</li><li>display approved RUN CLUB submissions where the required consent has been provided;</li><li>protect the website from abuse;</li><li>improve site performance and the shopping experience.</li></ul></EditorialSection>
<EditorialSection title="ANALYTICS"><p>We may use Google Analytics to understand website usage such as page views, device information and shopping interactions. Optional analytics must only run after the visitor chooses to allow analytics.</p></EditorialSection>
<EditorialSection title="BROWSER STORAGE & COOKIES"><p>Essential browser storage may be used for features such as the cart, authentication and preferences. Optional analytics storage is separate and can be declined without preventing the visitor from placing an order.</p></EditorialSection>
<EditorialSection title="SERVICE PROVIDERS"><p>RUN213 uses service providers necessary to operate the website, including Firebase, Vercel, Cloudinary, Upstash and Google Analytics. These providers may process information only as needed to provide their respective services.</p></EditorialSection>
<EditorialSection title="RUN CLUB CONTENT"><p>Approved RUN CLUB submissions may be displayed publicly when the required submission consent has been provided. If a user wants an approved submission reviewed or removed, they can contact RUN213.</p></EditorialSection>
<EditorialSection title="DATA RETENTION"><p>We keep information for as long as reasonably needed to provide the service, support orders, maintain required records and resolve issues. Some order information may need to be retained after an account deletion request where appropriate.</p></EditorialSection>
<EditorialSection title="YOUR CHOICES"><p>Users may request access, correction or deletion of personal information where applicable. Users may also decline optional analytics.</p></EditorialSection>
<EditorialSection title="DATA SALES"><p>RUN213 does not sell personal information.</p></EditorialSection>
<EditorialSection title="CONTACT"><p><Link href="mailto:213run.collab@gmail.com">213run.collab@gmail.com</Link></p></EditorialSection>
</EditorialPage>; }
