"use client";

import Image from "next/image";
import { useCallback, useEffect, useState } from "react";
import { AdminAccessGate } from "@/components/admin/AdminAccessGate";
import { AdminShell } from "@/components/admin/AdminShell";

type Status = "pending" | "approved" | "rejected";
type Submission = { id: string; name: string; contactType: string; contactValue: string; instagram: string | null; wilaya: string | null; caption: string | null; publicName: string; publicCaption: string | null; publicWilaya: string | null; monthKey: string; status: Status; consentAccepted: boolean; proofImage: { secureUrl: string; width: number; height: number; format?: string; bytes?: number; publicId?: string } | null; createdAt: string | null; rejectionReason: string | null };
type Summary = { pendingCount: number; approvedCount: number; rejectedCount: number; monthlyApprovedCount: number; maximumApproved: number; remaining: number; status: "open" | "full" };

export function AdminRunClubClient({ defaultMonth }: { defaultMonth: string }) {
  const [month, setMonth] = useState(defaultMonth); const [status, setStatus] = useState<Status>("pending"); const [summary, setSummary] = useState<Summary | null>(null); const [items, setItems] = useState<Submission[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [selected, setSelected] = useState<Submission | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const token = useCallback(async () => { const [{ auth }] = await Promise.all([import("@/lib/firebase/client"), import("firebase/auth")]); const user = auth.currentUser; if (!user) throw new Error("Admin sign-in required."); return user.getIdToken(); }, []);
  const load = useCallback(async (append = false) => { setLoading(true); setMessage(""); try { const authToken = await token(); const q = new URLSearchParams({ month, status, limit: "20" }); if (append && cursor) q.set("cursor", cursor); const [summaryResponse, listResponse] = await Promise.all([fetch(`/api/admin/run-club/summary?month=${month}`, { headers: { Authorization: `Bearer ${authToken}` } }), fetch(`/api/admin/run-club/submissions?${q}`, { headers: { Authorization: `Bearer ${authToken}` } })]); const summaryPayload = await summaryResponse.json(); const listPayload = await listResponse.json(); if (!summaryResponse.ok || !listResponse.ok) throw new Error(summaryPayload.message || listPayload.message || "Run Club data failed to load."); setSummary(summaryPayload); setItems((current) => append ? [...current, ...listPayload.submissions] : listPayload.submissions); setCursor(listPayload.nextCursor); } catch (error) { setMessage(error instanceof Error ? error.message : "Run Club data failed to load."); } finally { setLoading(false); } }, [cursor, month, status, token]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(false); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function moderate(action: "approve" | "reject") { if (!selected) return; setLoading(true); try { const authToken = await token(); const payload = action === "approve" ? { action, publicName: selected.publicName || selected.name, publicCaption: selected.publicCaption, publicWilaya: selected.publicWilaya } : { action, rejectionReason: selected.rejectionReason || null }; const response = await fetch(`/api/admin/run-club/submissions/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${authToken}` }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Moderation failed."); setMessage(action === "approve" ? "Submission approved." : "Submission rejected."); setSelected(null); await load(false); } catch (error) { setMessage(error instanceof Error ? error.message : "Moderation failed."); } finally { setLoading(false); } }
  return (
    <AdminShell title="Run Club" description="Review monthly run proof submissions.">
      <AdminAccessGate>
        <section className="adminCard adminRunClub">
          <div className="adminCard__heading"><p>RUN CLUB MODERATION</p><h2>Submission queue</h2><span>Approve only safe public fields. Private identity data stays Admin-only.</span></div>
          {summary && <div className="adminRunClubStats"><b>Pending {summary.pendingCount}</b><b>Approved {summary.approvedCount}</b><b>Rejected {summary.rejectedCount}</b><b>{summary.monthlyApprovedCount} / {summary.maximumApproved}</b><b>{summary.remaining} remaining</b><b>{summary.status.toUpperCase()}</b></div>}
          <div className="adminRunClubControls"><label>Month<input type="month" value={month} onChange={(e) => setMonth(e.target.value)} /></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value as Status)}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><button className="adminSecondary" onClick={() => void load(false)} type="button">Refresh</button></div>
          {message && <p className="adminNotice">{message}</p>}
          <div className="adminRunClubList">{items.map((item) => <button className={item.status === "pending" ? "adminRunClubItem isPending" : "adminRunClubItem"} key={item.id} type="button" onClick={() => setSelected(item)}>{item.proofImage && <Image src={item.proofImage.secureUrl} alt="Run proof thumbnail" width={80} height={80} />}<span><strong>{item.name}</strong><small>{item.contactType}: {item.contactValue}</small><small>{[item.instagram, item.wilaya, item.monthKey].filter(Boolean).join(" · ")}</small></span><b>{item.status}</b></button>)}</div>
          {cursor && <button className="adminSecondary" disabled={loading} onClick={() => void load(true)} type="button">Load more</button>}
        </section>
        {selected && <aside className="adminCard adminRunClubDetail"><div className="adminCard__heading"><p>SUBMISSION DETAIL</p><h2>{selected.name}</h2><span>{selected.status} · {selected.monthKey}</span></div>{selected.proofImage && <Image className="adminRunClubDetail__image" src={selected.proofImage.secureUrl} alt="Full run proof" width={720} height={720} />}<dl><dt>Contact</dt><dd>{selected.contactType}: {selected.contactValue}</dd><dt>Instagram</dt><dd>{selected.instagram || "—"}</dd><dt>Wilaya</dt><dd>{selected.wilaya || "—"}</dd><dt>Caption</dt><dd>{selected.caption || "—"}</dd><dt>Consent</dt><dd>{selected.consentAccepted ? "Accepted" : "Missing"}</dd><dt>Submitted</dt><dd>{selected.createdAt || "—"}</dd><dt>Image</dt><dd>{selected.proofImage ? `${selected.proofImage.width}×${selected.proofImage.height} · ${selected.proofImage.format ?? "image"} · ${selected.proofImage.bytes ?? 0} bytes` : "—"}</dd></dl><label>Public name<input value={selected.publicName} onChange={(e) => setSelected({ ...selected, publicName: e.target.value })} /></label><label>Public caption<textarea value={selected.publicCaption ?? ""} onChange={(e) => setSelected({ ...selected, publicCaption: e.target.value || null })} /></label><label>Public Wilaya<input value={selected.publicWilaya ?? ""} onChange={(e) => setSelected({ ...selected, publicWilaya: e.target.value || null })} /></label><label>Rejection reason<textarea value={selected.rejectionReason ?? ""} onChange={(e) => setSelected({ ...selected, rejectionReason: e.target.value || null })} /></label><div className="adminRunClubActions"><button className="adminPrimary" disabled={loading} onClick={() => void moderate("approve")} type="button">Approve</button><button className="adminDanger" disabled={loading} onClick={() => void moderate("reject")} type="button">Reject</button><button className="adminSecondary" onClick={() => setSelected(null)} type="button">Close</button></div></aside>}
      </AdminAccessGate>
    </AdminShell>
  );
}
