"use client";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { NEXT_STATUS, statusClass } from "@/components/admin/orders/adminOrderUtils";
import type { AdminOrderStatus } from "@/components/admin/orders/types";

export function AdminStatusMenu({ status, disabled, onChange }: { status: AdminOrderStatus; disabled?: boolean; onChange: (next: AdminOrderStatus, note?: string | null) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [modal, setModal] = useState<AdminOrderStatus | null>(null); const [note, setNote] = useState(""); const triggerRef = useRef<HTMLButtonElement | null>(null); const options = NEXT_STATUS[status];
  useEffect(() => { if (!modal) return; const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") closeModal(); }; document.body.style.overflow = "hidden"; window.addEventListener("keydown", onKey); return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", onKey); }; }, [modal]);
  function stop(event: React.SyntheticEvent) { event.preventDefault(); event.stopPropagation(); }
  function closeModal() { setModal(null); setNote(""); window.setTimeout(() => triggerRef.current?.focus(), 0); }
  async function run(next: AdminOrderStatus, reason?: string | null) { setBusy(true); try { await onChange(next, reason); setOpen(false); closeModal(); } finally { setBusy(false); } }
  async function pick(next: AdminOrderStatus, event: React.MouseEvent<HTMLButtonElement>) { stop(event); if (next === "cancelled" || next === "returned" || status === "cancelled" || status === "returned") { setModal(next); setOpen(false); return; } await run(next, null); }
  const modalNode = modal && typeof document !== "undefined" ? createPortal(<div className="adminStatusModal" role="presentation" onClick={(event) => { event.preventDefault(); event.stopPropagation(); closeModal(); }} onPointerDown={(event) => { event.stopPropagation(); }}><div className="adminStatusModal__card" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()} onPointerDown={(event) => event.stopPropagation()}><span>STATUS CONFIRMATION</span><h3>{label(modal, status)}?</h3><p>{status === "cancelled" && modal === "pending" ? "Inventory must be reserved again. RUN213 will verify current limited stock and block recovery if stock is unavailable." : status === "returned" && modal === "delivered" ? "This admin correction does not modify inventory automatically." : "Confirm this protected status transition."}</p><label><span>Optional reason</span><textarea value={note} onChange={(event) => setNote(event.target.value)} onClick={(event) => event.stopPropagation()} onPointerDown={(event) => event.stopPropagation()} placeholder="Reason for status history" rows={3} /></label><div><button className="button button--lime" type="button" disabled={busy} onClick={(event) => { stop(event); void run(modal, note.trim() || null); }}>CONFIRM</button><button className="button" type="button" disabled={busy} onClick={(event) => { stop(event); closeModal(); }}>CANCEL</button></div></div></div>, document.body) : null;
  return <div className="adminStatusMenu" onClick={(event) => event.stopPropagation()} onPointerDown={(event) => event.stopPropagation()}><button ref={triggerRef} className="adminStatusMenu__trigger" type="button" disabled={disabled || busy || !options.length} onClick={(event) => { stop(event); setOpen((value) => !value); }}><span className={statusClass(status)}>{status}</span><b>{busy ? "…" : "⌄"}</b></button>{open && options.length ? <div className="adminStatusMenu__list" role="menu">{options.map((next) => <button key={next} type="button" onClick={(event) => { void pick(next, event); }}><span className={statusClass(next)}>{label(next, status)}</span></button>)}</div> : null}{modalNode}</div>;
}

function label(next: AdminOrderStatus, current: AdminOrderStatus) { if (current === "cancelled" && next === "pending") return "RESTORE TO PENDING"; if (current === "returned" && next === "delivered") return "RESTORE TO DELIVERED"; return next; }
